create table if not exists public.receipt_manager_accounts (
  account_name text primary key,
  password_sha256 text not null,
  user_db text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.receipt_manager_sessions (
  session_id text primary key,
  account_name text not null,
  role text not null check (role in ('user', 'admin')),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table if exists public.receipt_manager_sessions
  drop constraint if exists receipt_manager_sessions_account_name_fkey;

create table if not exists public.receipt_manager_receipts (
  id bigint generated by default as identity primary key,
  account_name text not null references public.receipt_manager_accounts(account_name) on delete cascade,
  receipt_number text not null,
  amount numeric not null,
  category_key text not null,
  title text,
  receipt_date date,
  filename text,
  image_data_url text,
  image_storage_path text,
  ocr_provider text,
  ocr_raw_text text,
  ocr_confidence numeric,
  ocr_message text,
  ocr_needs_review boolean,
  created_at timestamptz not null default now()
);

create index if not exists receipt_manager_receipts_account_idx
  on public.receipt_manager_receipts(account_name, id);

create index if not exists receipt_manager_receipts_created_idx
  on public.receipt_manager_receipts(created_at desc);

create table if not exists public.receipt_manager_ai_summaries (
  account_name text primary key references public.receipt_manager_accounts(account_name) on delete cascade,
  summary_json jsonb not null,
  receipt_count integer not null,
  receipt_signature text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.receipt_manager_ai_events (
  id bigint generated by default as identity primary key,
  account_name text,
  provider text not null,
  operation text not null,
  status text not null check (status in ('success', 'warning', 'error')),
  http_status integer,
  message text not null,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists receipt_manager_ai_events_created_idx
  on public.receipt_manager_ai_events(id desc);
